project:
  type: website
  output-dir: docs
  
website:
  title: "Reiko Okamoto"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: talks-workshops.qmd
      - href: community-involvement.qmd
    right:
      - icon: github
        href: https://github.com/reikookamoto/reikookamoto.github.io
        target: _blank
  favicon: media/woman-technologist-light-skin-tone_1f469-1f3fb-200d-1f4bb.png

format:
  html:
    theme: [flatly, styles.scss]
    mainfont: Nunito
    toc: true
    page-layout: full

execute:
  freeze: auto