project:
  type: website
  output-dir: docs
  
website:
  #title: "Reiko Okamoto"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: outreach.qmd
        text: Outreach
      - href: software.qmd
        text: Software
      - href: CV/reiko_okamoto.pdf
        text: CV
  favicon: bullet-train_1f685.png

format:
  html:
    theme: zephyr
    css: styles.css
    toc: true

editor: visual

execute:
  freeze: auto